function CINDI_2_tg_pf_output_format(auto, version, species, data_path,data_source)

if nargin == 1
    if auto == 0
        %%%% input %%%%
        version = 'v2';
        species ='NO2_460nm';
        %%% profile data path %%%
        %data_path = 'C:\SCIATRAN2\TRACEGAS_RETRIEVAL_v-1-2\Campaign\Retrieval_settings_A\CINDI2\20160914_2\profiles\';
        %data_path = 'C:\SCIATRAN2\TRACEGAS_RETRIEVAL_v-1-2\Campaign\Retrieval_settings_A\20160912\profiles\';
%         data_path = 'C:\SCIATRAN2\TRACEGAS_RETRIEVAL_v-1-2\Campaign\Retrieval_settings_A\CINDI2\no_offset\20160915\profiles\';
        cd(data_path);
        %%% VCD %%%
        cd ..; cd general;
        file_nm_vcd = 'NO2_retrieval_20160915.dat';
        data_vcd = importfile_VCD(file_nm_vcd);
    elseif auto == 1
        disp('Warning: mising version, species, and data path info! ');
    end
    
elseif nargin ~= 5
    disp('Warning: mising version, species, and data path info! ');
else
    
    %%% VCD %%%
    cd ..; cd general;
    file_nm_vcd = ['NO2_retrieval_' data_path(end-8:end-1) '.dat'];
    data_vcd = importfile_VCD(file_nm_vcd);
    data_path = [data_path 'profiles/'];
end
            
cd(data_path);




%%%% read in data from the OEM %%%%
cd(data_path);
tmp=dir();
list={tmp.name};
list(1:2)=[];
time_stamp =list{1}(10:17);
yyyy = str2double(list{1}(10:13));
mm = str2double(list{1}(14:15));
dd = str2double(list{1}(16:17));
julian = Date2Julian(yyyy,mm,dd);
N = length(list);
for i = 1:1:N
    data = importfile_profiles(list{i});
    nd_profiles(:,i) = data.retr_nd;
    err_nd_profiles(:,i) = data.err_r_nd;
    apriori_profiles(:,i) = data.apriori;
    HHMM = list{1}(19:22);
    fday = datenum(HHMM,'HHMM');
    fday = fday - fix(fday) + julian;
    time_profiles(:,i) = fday;
    z = data.z;
end


%%% print data to CINDI-2 format %%%
cd ..;
if ~exist('cindi2','dir'), mkdir('cindi2'), end
cd cindi2;

nd_profile_name = ['U_Toronto_MAXDOAS_' data_source '_'  species '_CINDI2_' time_stamp '_' version '_profile.asc'];
dlmwrite(nd_profile_name,nd_profiles, 'delimiter','\t' ,'precision','%.8e');

err_nd_profile_name = ['U_Toronto_MAXDOAS_' data_source '_'  species '_CINDI2_' time_stamp '_' version '_err.asc'];
dlmwrite(err_nd_profile_name,err_nd_profiles,'delimiter','\t','precision','%.8e');

apriori_profile_name = ['U_Toronto_MAXDOAS_' data_source '_'  species '_CINDI2_' time_stamp '_' version '_apriori_profile.asc'];
dlmwrite(apriori_profile_name,apriori_profiles,'delimiter','\t','precision','%.8e');

time_profile_name = ['U_Toronto_MAXDOAS_' data_source '_'  species '_CINDI2_' time_stamp '_' version '_time.asc'];
dlmwrite(time_profile_name,time_profiles','delimiter','\t','precision','%.8e');

altitude_profile_name = ['U_Toronto_MAXDOAS_' data_source '_'  species '_CINDI2_' time_stamp '_' version '_altitude.asc'];
altitude_profiles = [z,z+0.2,z+0.1];
dlmwrite(altitude_profile_name,altitude_profiles,'delimiter','\t','precision','%.1e');

NO2_VCD_name = ['U_Toronto_MAXDOAS_' data_source '_'  species '_CINDI2_' time_stamp '_' version '_VCD.asc'];
NO2_VCD = data_vcd.NO2_VCD;
dlmwrite(NO2_VCD_name,NO2_VCD,'delimiter','\t','precision','%.8e');




function NO2prof201609140608 = importfile_profiles(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   NO2PROF201609140608 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   NO2PROF201609140608 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   NO2prof201609140608 = importfile('NO2_prof_20160914_0608.dat', 2, 22);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/20 11:42:22

%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
NO2prof201609140608 = table(dataArray{1:end-1}, 'VariableNames', {'z','apriori','err_apriori','retr_nd','err_r_nd','err_s_nd','err_m_nd','retr_vmr','err_r_vmr','err_s_vmr','err_m_vmr','retr_cnc','err_r_cnc','err_s_cnc','err_m_cnc'});

function NO2retrieval20160914 = importfile_VCD(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   NO2RETRIEVAL20160914 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   NO2RETRIEVAL20160914 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   NO2retrieval20160914 = importfile('NO2_retrieval_20160914.dat', 2, 14);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/20 09:58:44

%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{dd/MM/yyyy}D)
%	column2: datetimes (%{HH:mm:ss}D)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%13{dd/MM/yyyy}D%10{HH:mm:ss}D%8f%8f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
NO2retrieval20160914 = table(dataArray{1:end-1}, 'VariableNames', {'date','time','Nr','n_iter','chisq','H','d_s','gamma','gamma_max','NO2_VCD','err_NO2_VCD','Retr_height','surf_num_dens','err_surf_num_dens','surf_vmr','err_surf_vmr','surf_cnc','err_surf_cnc'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% NO2retrieval20160914.date=datenum(NO2retrieval20160914.date);
% NO2retrieval20160914.time=datenum(NO2retrieval20160914.time);

function avk201609140608 = importfile_avk(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   AVK201609140608 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   AVK201609140608 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   avk201609140608 = importfile('avk_20160914_0608.dat', 2, 22);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/20 13:22:06

%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: double (%f)
%	column15: double (%f)
%   column16: double (%f)
%	column17: double (%f)
%   column18: double (%f)
%	column19: double (%f)
%   column20: double (%f)
%	column21: double (%f)
%   column22: double (%f)
%	column23: double (%f)
%   column24: double (%f)
%	column25: double (%f)
%   column26: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*14s%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%14f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
avk201609140608 = [dataArray{1:end-1}];


